[package]
name = "ruby_magnus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
magnus = "0.6.3"

[lib]
name = "ruby_magnus"
crate-type = ["cdylib"]

[profile.release]
lto = true
