[package]
name = "ruby_rutie"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rutie = "0.9.0"
regex = "1.5.4"
lazy_static = "1.4.0"

[lib]
name = "ruby_rutie"
crate-type = ["cdylib"]
